A placeholder to add Dockerfile to the application
A dockerfile is only active when we need to have an active instance of the application running at all time.
    Will eventually be required when we need to have live price feeds incoming