CREATE OR REPLACE PROCEDURE statements_api_dbo.api_store_balance_sheet( IN P_SYMBOL_I VARCHAR(4),
                                                                        IN P_FISCAL_DATE_END_I DATE,
                                                                        IN P_CURRENCY_CD_I VARCHAR(4),
                                                                        IN P_TOTAL_ASSETS_I DECIMAL(20,0),
                                                                        IN P_TOTAL_CURR_ASSETS_I DECIMAL(20,0),
                                                                        IN P_CASH_AND_EQUIV_I DECIMAL(20,0),
                                                                        IN P_CASH_AND_SHORT_INV_I DECIMAL(20,0),
                                                                        IN P_INVENTORY_I DECIMAL(20,0),
                                                                        IN P_CURRENT_NET_REC_I DECIMAL(20,0),
                                                                        IN P_TOT_NON_CURR_ASSETS_I DECIMAL(20,0),
                                                                        IN P_PROPERTY_PLANT_EQUIP_I DECIMAL(20,0),
                                                                        IN P_ACCUM_DEPR_I DECIMAL(20,0),
                                                                        IN P_INTANG_ASSETS_I DECIMAL(20,0),
                                                                        IN P_INTANG_ASSETS_NO_GW_I DECIMAL(20,0),
                                                                        IN P_GOODWILL_I DECIMAL(20,0),
                                                                        IN P_INVESTMENTS_I DECIMAL(20,0),
                                                                        IN P_LT_INVESTMENTS_I DECIMAL(20,0),
                                                                        IN P_ST_INVESTMENTS_I DECIMAL(20,0),
                                                                        IN P_OTHER_CURR_ASSETS_I DECIMAL(20,0),
                                                                        IN P_OTHER_NONCURR_ASSETS_I DECIMAL(20,0),
                                                                        IN P_TOTAL_LIAB_I DECIMAL(20,0),
                                                                        IN P_TOTAL_CURR_LIAB_I DECIMAL(20,0),
                                                                        IN P_CURR_AP_I DECIMAL(20,0),
                                                                        IN P_DEFF_REVENUE_I DECIMAL(32,0),
                                                                        IN P_CURR_DEBT_I DECIMAL(20,0),
                                                                        IN P_ST_DEBT_I DECIMAL(20,0),
                                                                        IN P_TOT_NONCURR_LIAB_I DECIMAL(20,0),
                                                                        IN P_CURR_LT_DEBT_I DECIMAL(20,0),
                                                                        IN P_NONCURR_LT_DEBT_I DECIMAL(20,0),
                                                                        IN P_SHORT_LT_DEBT_TOTAL_I DECIMAL(20,0),
                                                                        IN P_TOT_SHAREHOLD_EQ_I DECIMAL(20,0),
                                                                        IN P_TREASURY_STOCK_I DECIMAL(20,0),
                                                                        IN P_RET_EARNINGS_I DECIMAL(20,0),
                                                                        IN P_COMMON_STOCK_I DECIMAL(20,0),
                                                                        IN P_COMMON_STOCK_OUT_I DECIMAL(20,0),
                                                                        IN P_CREATE_ID_I VARCHAR(10),
                                                                        IN P_CREATE_TS_I TIMESTAMP)
LANGUAGE plpgsql
AS $$
BEGIN
IF EXISTS (SELECT 1 FROM statements.balance_sheet tgt
                    WHERE P_SYMBOL_I = tgt.symbol
                        AND P_FISCAL_DATE_END_I = tgt.fiscal_date_end) THEN
  --existing record
  UPDATE statements.balance_sheet tgt
  SET
        tgt.CURRENCY_CD = P_CURRENCY_CD_I,
        tgt.TOTAL_ASSETS = P_TOTAL_ASSETS_I,
        tgt.TOTAL_CURR_ASSETS = P_TOTAL_CURR_ASSETS_I,
        tgt.CASH_AND_EQUIV = P_CASH_AND_EQUIV_I,
        tgt.CASH_AND_SHORT_INV = P_CASH_AND_SHORT_INV_I,
        tgt.INVENTORY = P_INVENTORY_I,
        tgt.CURRENT_NET_REC = P_CURRENT_NET_REC_I,
        tgt.TOT_NON_CURR_ASSETS = P_TOT_NON_CURR_ASSETS_I,
        tgt.PROPERTY_PLANT_EQUIP = P_PROPERTY_PLANT_EQUIP_I,
        tgt.ACCUM_DEPR = P_ACCUM_DEPR_I,
        tgt.INTANG_ASSETS = P_INTANG_ASSETS_I,
        tgt.INTANG_ASSETS_NO_GW = P_INTANG_ASSETS_NO_GW_I,
        tgt.GOODWILL = P_GOODWILL_I,
        tgt.INVESTMENTS = P_INVESTMENTS_I,
        tgt.LT_INVESTMENTS = P_LT_INVESTMENTS_I,
        tgt.ST_INVESTMENTS = P_ST_INVESTMENTS_I,
        tgt.OTHER_CURR_ASSETS = P_OTHER_CURR_ASSETS_I,
        tgt.OTHER_NONCURR_ASSETS = P_OTHER_NONCURR_ASSETS_I,
        tgt.TOTAL_LIAB = P_TOTAL_LIAB_I,
        tgt.TOTAL_CURR_LIAB = P_TOTAL_CURR_LIAB_I,
        tgt.CURR_AP = P_CURR_AP_I,
        tgt.DEFF_REVENUE = P_DEFF_REVENUE_I,
        tgt.CURR_DEBT = P_CURR_DEBT_I,
        tgt.ST_DEBT = P_ST_DEBT_I,
        tgt.TOT_NONCURR_LIAB = P_TOT_NONCURR_LIAB_I,
        tgt.CURR_LT_DEBT = P_CURR_LT_DEBT_I,
        tgt.NONCURR_LT_DEBT = P_NONCURR_LT_DEBT_I,
        tgt.SHORT_LT_DEBT_TOTAL = P_SHORT_LT_DEBT_TOTAL_I,
        tgt.TOT_SHAREHOLD_EQ = P_TOT_SHAREHOLD_EQ_I,
        tgt.TREASURY_STOCK = P_TREASURY_STOCK_I,
        tgt.RET_EARNINGS = P_RET_EARNINGS_I,
        tgt.COMMON_STOCK = P_COMMON_STOCK_I,
        tgt.COMMON_STOCK_OUT = P_COMMON_STOCK_OUT_I,
        tgt.UPDATE_ID = P_CREATE_ID_I,
        tgt.UPDATE_TS = P_CREATE_TS_I
WHERE
              P_SYMBOL_I = tgt.symbol
    AND P_FISCAL_DATE_END_I = tgt.fiscal_date_end;
ELSE --Record does not exist
   INSERT INTO statements.balance_sheet(SYMBOL,
                                                                    FISCAL_DATE_END,
                                                                    CURRENCY_CD,
                                                                    TOTAL_ASSETS,
                                                                    TOTAL_CURR_ASSETS,
                                                                    CASH_AND_EQUIV,
                                                                    CASH_AND_SHORT_INV,
                                                                    INVENTORY,
                                                                    CURRENT_NET_REC,
                                                                    TOT_NON_CURR_ASSETS,
                                                                    PROPERTY_PLANT_EQUIP, ACCUM_DEPR,
                                                                    INTANG_ASSETS,
                                                                    INTANG_ASSETS_NO_GW,
                                                                    GOODWILL,
                                                                    INVESTMENTS,
                                                                    LT_INVESTMENTS,
                                                                    ST_INVESTMENTS,
                                                                    OTHER_CURR_ASSETS,
                                                                    OTHER_NONCURR_ASSETS,
                                                                    TOTAL_LIAB,
                                                                    TOTAL_CURR_LIAB,
                                                                    CURR_AP,
                                                                    DEFF_REVENUE,
                                                                    CURR_DEBT,
                                                                    ST_DEBT,
                                                                    TOT_NONCURR_LIAB,
                                                                    CURR_LT_DEBT,
                                                                    NONCURR_LT_DEBT,
                                                                    SHORT_LT_DEBT_TOTAL,
                                                                    TOT_SHAREHOLD_EQ,
                                                                    TREASURY_STOCK,
                                                                    RET_EARNINGS,
                                                                    COMMON_STOCK,
                                                                    COMMON_STOCK_OUT,
                                                                    CREATE_ID,
                                                                    CREATE_TS,
                                                                    UPDATE_ID,
                                                                    UPDATE_TS)
                                          VALUES         (P_SYMBOL_I,
                                                                    P_FISCAL_DATE_END_I,
                                                                    P_CURRENCY_CD_I,
                                                                    P_TOTAL_ASSETS_I,
                                                                    P_TOTAL_CURR_ASSETS_I,
                                                                    P_CASH_AND_EQUIV_I,
                                                                    P_CASH_AND_SHORT_INV_I,
                                                                    P_INVENTORY_I,
                                                                    P_CURRENT_NET_REC_I,
                                                                    P_TOT_NON_CURR_ASSETS_I,
                                                                    P_PROPERTY_PLANT_EQUIP_I,
                                                                    P_ACCUM_DEPR_I,
                                                                    P_INTANG_ASSETS_I,
                                                                    P_INTANG_ASSETS_NO_GW_I,
                                                                    P_GOODWILL_I,
                                                                    P_INVESTMENTS_I,
                                                                    P_LT_INVESTMENTS_I,
                                                                    P_ST_INVESTMENTS_I,
                                                                    P_OTHER_CURR_ASSETS_I,
                                                                    P_OTHER_NONCURR_ASSETS_I,
                                                                    P_TOTAL_LIAB_I,
                                                                    P_TOTAL_CURR_LIAB_I,
                                                                    P_CURR_AP_I,
                                                                    P_DEFF_REVENUE_I,
                                                                    P_CURR_DEBT_I,
                                                                    P_ST_DEBT_I,
                                                                    P_TOT_NONCURR_LIAB_I,
                                                                    P_CURR_LT_DEBT_I,
                                                                    P_NONCURR_LT_DEBT_I,
                                                                    P_SHORT_LT_DEBT_TOTAL_I,
                                                                    P_TOT_SHAREHOLD_EQ_I,
                                                                    P_TREASURY_STOCK_I,
                                                                    P_RET_EARNINGS_I,
                                                                    P_COMMON_STOCK_I,
                                                                    P_COMMON_STOCK_OUT_I,
                                                                    P_CREATE_ID_I,
                                                                    P_CREATE_TS_I,
                                                                    NULL,
                                                                    NULL);
END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Error in procedure STATEMENTS_API_DBO.api_store_balance_sheet (%)',SQLERRM;
END;
$$;