CREATE OR REPLACE PROCEDURE statements_api_dbo.api_store_balance_sheet( IN P_SYMBOL_I VARCHAR(4),
                                                                        IN P_FISCAL_DATE_END_I DATE,
                                                                        IN P_CURRENCY_CD_I VARCHAR(4),
                                                                        IN P_TOTAL_ASSETS_I DECIMAL(20,0),
                                                                        IN P_TOTAL_CURR_ASSETS_I DECIMAL(20,0),
                                                                        IN P_CASH_AND_EQUIV_I DECIMAL(20,0),
                                                                        IN P_CASH_AND_SHORT_INV_I DECIMAL(20,0),
                                                                        IN P_INVENTORY_I DECIMAL(20,0),
                                                                        IN P_CURRENT_NET_REC_I DECIMAL(20,0),
                                                                        IN P_TOT_NON_CURR_ASSETS_I DECIMAL(20,0),
                                                                        IN P_PROPERTY_PLANT_EQUIP_I DECIMAL(20,0),
                                                                        IN P_ACCUM_DEPR_I DECIMAL(20,0),
                                                                        IN P_INTANG_ASSETS_I DECIMAL(20,0),
                                                                        IN P_INTANG_ASSETS_NO_GW_I DECIMAL(20,0),
                                                                        IN P_GOODWILL_I DECIMAL(20,0),
                                                                        IN P_INVESTMENTS_I DECIMAL(20,0),
                                                                        IN P_LT_INVESTMENTS_I DECIMAL(20,0),
                                                                        IN P_ST_INVESTMENTS_I DECIMAL(20,0),
                                                                        IN P_OTHER_CURR_ASSETS_I DECIMAL(20,0),
                                                                        IN P_OTHER_NONCURR_ASSETS_I DECIMAL(20,0),
                                                                        IN P_TOTAL_LIAB_I DECIMAL(20,0),
                                                                        IN P_TOTAL_CURR_LIAB_I DECIMAL(20,0),
                                                                        IN P_CURR_AP_I DECIMAL(20,0),
                                                                        IN P_DEFF_REVENUE_I DECIMAL(32,0),
                                                                        IN P_CURR_DEBT_I DECIMAL(20,0),
                                                                        IN P_ST_DEBT_I DECIMAL(20,0),
                                                                        IN P_TOT_NONCURR_LIAB_I DECIMAL(20,0),
                                                                        IN P_CURR_LT_DEBT_I DECIMAL(20,0),
                                                                        IN P_NONCURR_LT_DEBT_I DECIMAL(20,0),
                                                                        IN P_SHORT_LT_DEBT_TOTAL_I DECIMAL(20,0),
                                                                        IN P_TOT_SHAREHOLD_EQ_I DECIMAL(20,0),
                                                                        IN P_TREASURY_STOCK_I DECIMAL(20,0),
                                                                        IN P_RET_EARNINGS_I DECIMAL(20,0),
                                                                        IN P_COMMON_STOCK_I DECIMAL(20,0),
                                                                        IN P_COMMON_STOCK_OUT_I DECIMAL(20,0),
                                                                        IN P_CREATE_ID_I VARCHAR(10),
                                                                        IN P_CREATE_TS_I TIMESTAMP)
LANGUAGE plpgsql
AS $$
DECLARE
  v_exists BOOLEAN;
BEGIN
SELECT TRUE INTO v_exists 
FROM statements.balance_sheet tgt
WHERE tgt.SYMBOL = P_SYMBOL_I
AND tgt.FISCAL_DATE_END = P_FISCAL_DATE_END_I;

IF v_exists THEN
  UPDATE statements.balance_sheet
  SET
        CURRENCY_CD = P_CURRENCY_CD_I,
        TOTAL_ASSETS = P_TOTAL_ASSETS_I,
        TOTAL_CURR_ASSETS = P_TOTAL_CURR_ASSETS_I,
        CASH_AND_EQUIV = P_CASH_AND_EQUIV_I,
        CASH_AND_SHORT_INV = P_CASH_AND_SHORT_INV_I,
        INVENTORY = P_INVENTORY_I,
        CURRENT_NET_REC = P_CURRENT_NET_REC_I,
        TOT_NON_CURR_ASSETS = P_TOT_NON_CURR_ASSETS_I,
        PROPERTY_PLANT_EQUIP = P_PROPERTY_PLANT_EQUIP_I,
        ACCUM_DEPR = P_ACCUM_DEPR_I,
        INTANG_ASSETS = P_INTANG_ASSETS_I,
        INTANG_ASSETS_NO_GW = P_INTANG_ASSETS_NO_GW_I,
        GOODWILL = P_GOODWILL_I,
        INVESTMENTS = P_INVESTMENTS_I,
        LT_INVESTMENTS = P_LT_INVESTMENTS_I,
        ST_INVESTMENTS = P_ST_INVESTMENTS_I,
        OTHER_CURR_ASSETS = P_OTHER_CURR_ASSETS_I,
        OTHER_NONCURR_ASSETS = P_OTHER_NONCURR_ASSETS_I,
        TOTAL_LIAB = P_TOTAL_LIAB_I,
        TOTAL_CURR_LIAB = P_TOTAL_CURR_LIAB_I,
        CURR_AP = P_CURR_AP_I,
        DEFF_REVENUE = P_DEFF_REVENUE_I,
        CURR_DEBT = P_CURR_DEBT_I,
        ST_DEBT = P_ST_DEBT_I,
        TOT_NONCURR_LIAB = P_TOT_NONCURR_LIAB_I,
        CURR_LT_DEBT = P_CURR_LT_DEBT_I,
        NONCURR_LT_DEBT = P_NONCURR_LT_DEBT_I,
        SHORT_LT_DEBT_TOTAL = P_SHORT_LT_DEBT_TOTAL_I,
        TOT_SHAREHOLD_EQ = P_TOT_SHAREHOLD_EQ_I,
        TREASURY_STOCK = P_TREASURY_STOCK_I,
        RET_EARNINGS = P_RET_EARNINGS_I,
        COMMON_STOCK = P_COMMON_STOCK_I,
        COMMON_STOCK_OUT = P_COMMON_STOCK_OUT_I,
        UPDATE_ID = P_CREATE_ID_I,
        UPDATE_TS = P_CREATE_TS_I
  WHERE
              SYMBOL = P_SYMBOL_I
    AND FISCAL_DATE_END = P_FISCAL_DATE_END_I;
ELSE
   INSERT INTO statements.balance_sheet(SYMBOL,
                                                                    FISCAL_DATE_END,
                                                                    CURRENCY_CD,
                                                                    TOTAL_ASSETS,
                                                                    TOTAL_CURR_ASSETS,
                                                                    CASH_AND_EQUIV,
                                                                    CASH_AND_SHORT_INV,
                                                                    INVENTORY,
                                                                    CURRENT_NET_REC,
                                                                    TOT_NON_CURR_ASSETS,
                                                                    PROPERTY_PLANT_EQUIP, ACCUM_DEPR,
                                                                    INTANG_ASSETS,
                                                                    INTANG_ASSETS_NO_GW,
                                                                    GOODWILL,
                                                                    INVESTMENTS,
                                                                    LT_INVESTMENTS,
                                                                    ST_INVESTMENTS,
                                                                    OTHER_CURR_ASSETS,
                                                                    OTHER_NONCURR_ASSETS,
                                                                    TOTAL_LIAB,
                                                                    TOTAL_CURR_LIAB,
                                                                    CURR_AP,
                                                                    DEFF_REVENUE,
                                                                    CURR_DEBT,
                                                                    ST_DEBT,
                                                                    TOT_NONCURR_LIAB,
                                                                    CURR_LT_DEBT,
                                                                    NONCURR_LT_DEBT,
                                                                    SHORT_LT_DEBT_TOTAL,
                                                                    TOT_SHAREHOLD_EQ,
                                                                    TREASURY_STOCK,
                                                                    RET_EARNINGS,
                                                                    COMMON_STOCK,
                                                                    COMMON_STOCK_OUT,
                                                                    CREATE_ID,
                                                                    CREATE_TS,
                                                                    UPDATE_ID,
                                                                    UPDATE_TS)
                                          VALUES         (P_SYMBOL_I,
                                                                    P_FISCAL_DATE_END_I,
                                                                    P_CURRENCY_CD_I,
                                                                    P_TOTAL_ASSETS_I,
                                                                    P_TOTAL_CURR_ASSETS_I,
                                                                    P_CASH_AND_EQUIV_I,
                                                                    P_CASH_AND_SHORT_INV_I,
                                                                    P_INVENTORY_I,
                                                                    P_CURRENT_NET_REC_I,
                                                                    P_TOT_NON_CURR_ASSETS_I,
                                                                    P_PROPERTY_PLANT_EQUIP_I,
                                                                    P_ACCUM_DEPR_I,
                                                                    P_INTANG_ASSETS_I,
                                                                    P_INTANG_ASSETS_NO_GW_I,
                                                                    P_GOODWILL_I,
                                                                    P_INVESTMENTS_I,
                                                                    P_LT_INVESTMENTS_I,
                                                                    P_ST_INVESTMENTS_I,
                                                                    P_OTHER_CURR_ASSETS_I,
                                                                    P_OTHER_NONCURR_ASSETS_I,
                                                                    P_TOTAL_LIAB_I,
                                                                    P_TOTAL_CURR_LIAB_I,
                                                                    P_CURR_AP_I,
                                                                    P_DEFF_REVENUE_I,
                                                                    P_CURR_DEBT_I,
                                                                    P_ST_DEBT_I,
                                                                    P_TOT_NONCURR_LIAB_I,
                                                                    P_CURR_LT_DEBT_I,
                                                                    P_NONCURR_LT_DEBT_I,
                                                                    P_SHORT_LT_DEBT_TOTAL_I,
                                                                    P_TOT_SHAREHOLD_EQ_I,
                                                                    P_TREASURY_STOCK_I,
                                                                    P_RET_EARNINGS_I,
                                                                    P_COMMON_STOCK_I,
                                                                    P_COMMON_STOCK_OUT_I,
                                                                    P_CREATE_ID_I,
                                                                    P_CREATE_TS_I,
                                                                    NULL,
                                                                    NULL);
END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Error in procedure STATEMENTS_API_DBO.api_store_balance_sheet (%)',SQLERRM;
END;
$$;