CREATE OR REPLACE PROCEDURE statements_api_dbo.api_store_income_statement(IN P_SYMBOL_I VARCHAR(4),
                                                                        IN P_FISCAL_DATE_END_I DATE,
                                                                        IN P_CURRENCY_CD_I VARCHAR(4),
                                                                        IN P_GROSS_PROFIT_I DECIMAL(20,0),
                                                                        IN P_TOTAL_REVENUE_I DECIMAL(20,0),
                                                                        IN P_COST_OF_REVENUE_I DECIMAL(20,0),
                                                                        IN P_COGS_I DECIMAL(20,0),
                                                                        IN P_OP_INCOME_I DECIMAL(20,0),
                                                                        IN P_SELLING_ADMIN_EXP_I DECIMAL(20,0),
                                                                        IN P_RESEARCH_AND_DEV_I DECIMAL(20,0),
                                                                        IN P_OP_EXPENSES_I DECIMAL(20,0),
                                                                        IN P_INV_INCOME_NET_I DECIMAL(20,0),
                                                                        IN P_NET_INTEREST_INC_I DECIMAL(20,0),
                                                                        IN P_INTEREST_INC_I DECIMAL(20,0),
                                                                        IN P_INTEREST_EXP_I DECIMAL(20,0),
                                                                        IN P_NON_INTEREST_INC_I DECIMAL(20,0),
                                                                        IN P_OTHER_NONOP_INCOME_I DECIMAL(20,0),
                                                                        IN P_DEPRECIATION_I DECIMAL(20,0),
                                                                        IN P_DEPR_AND_AMORT_I DECIMAL(20,0),
                                                                        IN P_INC_BEFORE_TAX_I DECIMAL(20,0),
                                                                        IN P_INC_TAX_EXP_I DECIMAL(20,0),
                                                                        IN P_INT_AND_DEBT_EXP_I DECIMAL(20,0),
                                                                        IN P_NET_INC_CONT_OP_I DECIMAL(20,0),
                                                                        IN P_COMP_INC_NET_TAX_I DECIMAL(20,0),
                                                                        IN P_EBIT_I DECIMAL(20,0),
                                                                        IN P_EBITDA_I DECIMAL(20,0),
                                                                        IN P_NET_INCOME_I DECIMAL(20,0),
                                                                        IN P_CREATE_ID_I VARCHAR(10),
                                                                        IN P_CREATE_TS_I TIMESTAMP)
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM statements.income_statement
                      WHERE P_SYMBOL_I = symbol
                          AND  P_FISCAL_DATE_END_I = fiscal_date_end) THEN
    UPDATE statements.income_statement
    SET CURRENCY_CD = P_CURRENCY_CD_I,
            GROSS_PROFIT = P_GROSS_PROFIT_I,
            TOTAL_REVENUE = P_TOTAL_REVENUE_I,
            COST_OF_REVENUE = P_COST_OF_REVENUE_I,
            COGS = P_COGS_I,
            OP_INCOME = P_OP_INCOME_I,
            SELLING_ADMIN_EXP = P_SELLING_ADMIN_EXP_I,
            RESEARCH_AND_DEV = P_RESEARCH_AND_DEV_I,
            OP_EXPENSES = P_OP_EXPENSES_I,
            INV_INCOME_NET = P_INV_INCOME_NET_I,
            NET_INTEREST_INC = P_NET_INTEREST_INC_I,
            INTEREST_INC = P_INTEREST_INC_I,
            INTEREST_EXP = P_INTEREST_EXP_I,
            NON_INTEREST_INC = P_NON_INTEREST_INC_I,
            OTHER_NONOP_INCOME = P_OTHER_NONOP_INCOME_I,
            DEPRECIATION = P_DEPRECIATION_I,
            DEPR_AND_AMORT = P_DEPR_AND_AMORT_I,
            INC_BEFORE_TAX = P_INC_BEFORE_TAX_I,
            INC_TAX_EXP = P_INC_TAX_EXP_I,
            INT_AND_DEBT_EXP = P_INT_AND_DEBT_EXP_I,
            NET_INC_CONT_OP = P_NET_INC_CONT_OP_I,
            COMP_INC_NET_TAX = P_COMP_INC_NET_TAX_I,
            EBIT = P_EBIT_I,
            EBITDA = P_EBITDA_I,
            NET_INCOME = P_NET_INCOME_I,
            UPDATE_ID = P_CREATE_ID_I,
            UPDATE_TS = P_CREATE_TS_I
    WHERE
          P_SYMBOL_I = symbol
        AND  P_FISCAL_DATE_END_I = fiscal_date_end;
  ELSE
    INSERT INTO statements.income_statement(SYMBOL,
                                                                              FISCAL_DATE_END,
                                                                              CURRENCY_CD,
                                                                              GROSS_PROFIT,
                                                                              TOTAL_REVENUE,
                                                                              COST_OF_REVENUE,
                                                                              COGS,
                                                                              OP_INCOME,
                                                                              SELLING_ADMIN_EXP,
                                                                              RESEARCH_AND_DEV,
                                                                              OP_EXPENSES,
                                                                              INV_INCOME_NET,
                                                                              NET_INTEREST_INC,
                                                                              INTEREST_INC,
                                                                              INTEREST_EXP,
                                                                              NON_INTEREST_INC,
                                                                              OTHER_NONOP_INCOME,
                                                                              DEPRECIATION,
                                                                              DEPR_AND_AMORT,
                                                                              INC_BEFORE_TAX,
                                                                              INC_TAX_EXP,
                                                                              INT_AND_DEBT_EXP,
                                                                              NET_INC_CONT_OP,
                                                                              COMP_INC_NET_TAX,
                                                                              EBIT,
                                                                              EBITDA,
                                                                              NET_INCOME,
                                                                              CREATE_ID,
                                                                              CREATE_TS,
                                                                              UPDATE_ID,
                                                                              UPDATE_TS )
                                                    VALUES         (P_SYMBOL_I,
                                                                              P_FISCAL_DATE_END_I,
                                                                              P_CURRENCY_CD_I,
                                                                              P_GROSS_PROFIT_I,
                                                                              P_TOTAL_REVENUE_I,
                                                                              P_COST_OF_REVENUE_I,
                                                                              P_COGS_I,
                                                                              P_OP_INCOME_I,
                                                                              P_SELLING_ADMIN_EXP_I,
                                                                              P_RESEARCH_AND_DEV_I,
                                                                              P_OP_EXPENSES_I,
                                                                              P_INV_INCOME_NET_I,
                                                                              P_NET_INTEREST_INC_I,
                                                                              P_INTEREST_INC_I,
                                                                              P_INTEREST_EXP_I,
                                                                              P_NON_INTEREST_INC_I,
                                                                              P_OTHER_NONOP_INCOME_I,
                                                                              P_DEPRECIATION_I,
                                                                              P_DEPR_AND_AMORT_I,
                                                                              P_INC_BEFORE_TAX_I,
                                                                              P_INC_TAX_EXP_I,
                                                                              P_INT_AND_DEBT_EXP_I,
                                                                              P_NET_INC_CONT_OP_I,
                                                                              P_COMP_INC_NET_TAX_I,
                                                                              P_EBIT_I,
                                                                              P_EBITDA_I,
                                                                              P_NET_INCOME_I,
                                                                              P_CREATE_ID_I,
                                                                              P_CREATE_TS_I,
                                                                              null,
                                                                              null);
    END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE EXCEPTION 'Error in procedure STATEMENTS_API_DBO.api_store_income_statement (%)',SQLERRM;
END;
$$ LANGUAGE plpgsql;