CREATE OR REPLACE PROCEDURE statements_api_dbo.api_store_cash_flows(IN P_SYMBOL_I VARCHAR(4),
                                                                    IN P_FISCAL_DATE_END_I DATE,
                                                                    IN P_CURRENCY_CD_I VARCHAR(4),
                                                                        IN P_OP_CASH_FLOW_I DECIMAL(20,0),
                                                                        IN P_PAYMENTS_TO_OP_I DECIMAL(20,0),
                                                                        IN P_PROCEEDS_FROM_OP_I DECIMAL(20,0),
                                                                        IN P_CHG_IN_OP_LIAB_I DECIMAL(20,0),
                                                                        IN P_CHG_IN_OP_ASST_I DECIMAL(20,0),
                                                                        IN P_DEPR_AND_AMORT_DEPLETION_I DECIMAL(20,0),
                                                                        IN P_CAPITAL_EXPENDITURES_I DECIMAL(20,0),
                                                                        IN P_CHG_IN_RECEIVABLES_I DECIMAL(20,0),
                                                                        IN P_CHG_IN_INVENTORY_I DECIMAL(20,0),
                                                                        IN P_PROFIT_I DECIMAL(20,0),
                                                                        IN P_CASHFLOW_INVEST_I DECIMAL(20,0),
                                                                        IN P_CASHFLOW_FINANCING_I DECIMAL(20,0),
                                                                        IN P_ST_DEBT_REPAY_PROC_I DECIMAL(20,0),
                                                                        IN P_COM_STCK_REPUR_PAYM_I DECIMAL(20,0),
                                                                        IN P_EQUITY_REPUR_PAYM_I DECIMAL(20,0),
                                                                        IN P_PREF_STCK_REPUR_PAYM_I DECIMAL(20,0),
                                                                        IN P_DIV_PAYOUT_I DECIMAL(20,0),
                                                                        IN P_DIV_PAYOUT_COM_STCK_I DECIMAL(20,0),
                                                                        IN P_DIV_PAYOUT_PREF_STCK_I DECIMAL(20,0),
                                                                        IN P_COM_STCK_ISSUE_PROC_I DECIMAL(20,0),
                                                                        IN P_LT_DEBT_ISSUE_PROCEEDS_I DECIMAL(20,0),
                                                                        IN P_PREF_STOCK_ISSUE_PROC_I DECIMAL(20,0),
                                                                        IN P_EQUITY_REPUR_PROC_I DECIMAL(20,0),
                                                                        IN P_TRES_STOCK_SALE_PROC_I DECIMAL(20,0),
                                                                        IN P_CHG_IN_CSH_EQUIV_I DECIMAL(20,0),
                                                                        IN P_CHG_IN_EXCHG_RT_I DECIMAL(20,0),
                                                                        IN P_NET_INCOME_I DECIMAL(20,0),
                                                                        IN P_CREATE_ID_I VARCHAR(10),
                                                                        IN P_CREATE_TS_I TIMESTAMP)
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM statements.CASH_FLOW
            WHERE P_SYMBOL_I = SYMBOL
              AND P_FISCAL_DATE_END_I = FISCAL_DATE_END) THEN
    UPDATE STATEMENTS.CASH_FLOW
    SET CURRENCY_CD = P_CURRENCY_CD_I,
        OP_CASH_FLOW = P_OP_CASH_FLOW_I,
        PAYMENTS_TO_OP = P_PAYMENTS_TO_OP_I,
        PROCEEDS_FROM_OP = P_PROCEEDS_FROM_OP_I,
        CHG_IN_OP_LIAB = P_CHG_IN_OP_LIAB_I,
        CHG_IN_OP_ASST = P_CHG_IN_OP_ASST_I,
        DEPR_AND_AMORT_DEPLETION = P_DEPR_AND_AMORT_DEPLETION_I,
        CAPITAL_EXPENDITURES = P_CAPITAL_EXPENDITURES_I,
        CHG_IN_RECEIVABLES = P_CHG_IN_RECEIVABLES_I,
        CHG_IN_INVENTORY = P_CHG_IN_INVENTORY_I,
        PROFIT = P_PROFIT_I,
        CASHFLOW_INVEST = P_CASHFLOW_INVEST_I,
        CASHFLOW_FINANCING = P_CASHFLOW_FINANCING_I,
        ST_DEBT_REPAY_PROC = P_ST_DEBT_REPAY_PROC_I,
        COM_STCK_REPUR_PAYM = P_COM_STCK_REPUR_PAYM_I,
        EQUITY_REPUR_PAYM = P_EQUITY_REPUR_PAYM_I,
        PREF_STCK_REPUR_PAYM = P_PREF_STCK_REPUR_PAYM_I,
        DIV_PAYOUT = P_DIV_PAYOUT_I,
        DIV_PAYOUT_COM_STCK = P_DIV_PAYOUT_COM_STCK_I,
        DIV_PAYOUT_PREF_STCK = P_DIV_PAYOUT_PREF_STCK_I,
        COM_STCK_ISSUE_PROC = P_COM_STCK_ISSUE_PROC_I,
        LT_DEBT_ISSUE_PROCEEDS = P_LT_DEBT_ISSUE_PROCEEDS_I,
        PREF_STOCK_ISSUE_PROC = P_PREF_STOCK_ISSUE_PROC_I,
        EQUITY_REPUR_PAYM = P_EQUITY_REPUR_PAYM_I,
        TRES_STOCK_SALE_PROC = P_TRES_STOCK_SALE_PROC_I,
        CHG_IN_CSH_EQUIV = P_CHG_IN_CSH_EQUIV_I,
        CHG_IN_EXCHG_RT = P_CHG_IN_EXCHG_RT_I,
        NET_INCOME = P_NET_INCOME_I,
        UPDATE_ID = P_CREATE_ID_I,
        UPDATE_TS = P_CREATE_TS_I
    WHERE
        P_SYMBOL_I = SYMBOL
      AND P_FISCAL_DATE_END_I = FISCAL_DATE_END;
    ELSE
        INSERT INTO STATEMENTS.CASH_FLOW(SYMBOL,
                                        FISCAL_DATE_END,
                                        CURRENCY_CD,
                                        OP_CASH_FLOW,
                                        PAYMENTS_TO_OP,
                                        PROCEEDS_FROM_OP,
                                        CHG_IN_OP_LIAB,
                                        CHG_IN_OP_ASST,
                                        DEPR_AND_AMORT_DEPLETION,
                                        CAPITAL_EXPENDITURES,
                                        CHG_IN_RECEIVABLES,
                                        CHG_IN_INVENTORY,
                                        PROFIT,
                                        CASHFLOW_INVEST,
                                        CASHFLOW_FINANCING,
                                        ST_DEBT_REPAY_PROC,
                                        COM_STCK_REPUR_PAYM,
                                        EQUITY_REPUR_PAYM,
                                        PREF_STCK_REPUR_PAYM,
                                        DIV_PAYOUT,
                                        DIV_PAYOUT_COM_STCK,
                                        DIV_PAYOUT_PREF_STCK,
                                        COM_STCK_ISSUE_PROC,
                                        LT_DEBT_ISSUE_PROCEEDS,
                                        PREF_STOCK_ISSUE_PROC,
                                        EQUITY_REPUR_PROC,
                                        TRES_STOCK_SALE_PROC,
                                        CHG_IN_CSH_EQUIV,
                                        CHG_IN_EXCHG_RT,
                                        NET_INCOME,
                                        CREATE_ID,
                                        CREATE_TS,
                                        UPDATE_ID,
                                        UPDATE_TS)
                            VALUES      (P_SYMBOL_I,
                                        P_FISCAL_DATE_END_I,
                                        P_CURRENCY_CD_I,
                                        P_OP_CASH_FLOW_I,
                                        P_PAYMENTS_TO_OP_I,
                                        P_PROCEEDS_FROM_OP_I,
                                        P_CHG_IN_OP_LIAB_I,
                                        P_CHG_IN_OP_ASST_I,
                                        P_DEPR_AND_AMORT_DEPLETION_I,
                                        P_CAPITAL_EXPENDITURES_I,
                                        P_CHG_IN_RECEIVABLES_I,
                                        P_CHG_IN_INVENTORY_I,
                                        P_PROFIT_I,
                                        P_CASHFLOW_INVEST_I,
                                        P_CASHFLOW_FINANCING_I,
                                        P_ST_DEBT_REPAY_PROC_I,
                                        P_COM_STCK_REPUR_PAYM_I,
                                        P_EQUITY_REPUR_PAYM_I,
                                        P_PREF_STCK_REPUR_PAYM_I,
                                        P_DIV_PAYOUT_I,
                                        P_DIV_PAYOUT_COM_STCK_I,
                                        P_DIV_PAYOUT_PREF_STCK_I,
                                        P_COM_STCK_ISSUE_PROC_I,
                                        P_LT_DEBT_ISSUE_PROCEEDS_I,
                                        P_PREF_STOCK_ISSUE_PROC_I,
                                        P_EQUITY_REPUR_PAYM_I,
                                        P_TRES_STOCK_SALE_PROC_I,
                                        P_CHG_IN_CSH_EQUIV_I,
                                        P_CHG_IN_EXCHG_RT_I,
                                        P_NET_INCOME_I,
                                        P_CREATE_ID_I,
                                        P_CREATE_TS_I,
                                        NULL,
                                        NULL);
    END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE EXCEPTION 'Error in procedure STATEMENTS_API_DBO.api_store_cash_flows (%)', SQLERRM;
END;
$$ LANGUAGE plpgsql;