CREATE OR REPLACE FUNCTION statements_api_dbo.api_fetch_cash_flows( IN P_SYMBOL_I VARCHAR(4),
                                                                    IN P_FISCAL_DATE_END_I DATE)
RETURNS TABLE (  P_SYMBOL_O VARCHAR(4),
                  P_FISCAL_DATE_END_O DATE,
                  P_CURRENCY_CD_O VARCHAR(4),
                  P_OP_CASH_FLOW_O DECIMAL(20,0),
                  P_PAYMENTS_TO_OP_O DECIMAL(20,0),
                  P_PROCEEDS_FROM_OP_O DECIMAL(20,0),
                  P_CHG_IN_OP_LIAB_O DECIMAL(20,0),
                  P_CHG_IN_OP_ASST_O DECIMAL(20,0),
                  P_DEPR_AND_AMORT_DEPLETION_O DECIMAL(20,0),
                  P_CAPITAL_EXPENDITURES_O DECIMAL(20,0),
                  P_CHG_IN_RECEIVABLES_O DECIMAL(20,0),
                  P_CHG_IN_INVENTORY_O DECIMAL(20,0),
                  P_PROFIT_O DECIMAL(20,0),
                  P_CASHFLOW_INVEST_O DECIMAL(20,0),
                  P_CASHFLOW_FINANCING_O DECIMAL(20,0),
                  P_ST_DEBT_REPAY_PROC_O DECIMAL(20,0),
                  P_COM_STCK_REPUR_PAYM_O DECIMAL(20,0),
                  P_EQUITY_REPUR_PAYM_O DECIMAL(20,0),
                  P_PREF_STCK_REPUR_PAYM_O DECIMAL(20,0),
                  P_DIV_PAYOUT_O DECIMAL(20,0),
                  P_DIV_PAYOUT_COM_STCK_O DECIMAL(20,0),
                  P_DIV_PAYOUT_PREF_STCK_O DECIMAL(20,0),
                  P_COM_STCK_ISSUE_PROC_O DECIMAL(20,0),
                  P_LT_DEBT_ISSUE_PROCEEDS_O DECIMAL(20,0),
                  P_PREF_STOCK_ISSUE_PROC_O DECIMAL(20,0),
                  P_EQUITY_REPUR_PROC_O DECIMAL(20,0),
                  P_TRES_STOCK_SALE_PROC_O DECIMAL(20,0),
                  P_CHG_IN_CSH_EQUIV_O DECIMAL(20,0),
                  P_CHG_IN_EXCHG_RT_O DECIMAL(20,0),
                  P_NET_INCOME_O DECIMAL(20,0),
                  P_CREATE_ID_O VARCHAR(10),
                  P_CREATE_TS_O TIMESTAMP,
                  P_UPDATE_ID_O VARCHAR(10),
                  P_UPDATE_TS_O TIMESTAMP)
AS $$
BEGIN
  RETURN QUERY SELECT SYMBOL,
                        FISCAL_DATE_END,
                        CURRENCY_CD,
                        OP_CASH_FLOW,
                        PAYMENTS_TO_OP,
                        PROCEEDS_FROM_OP,
                        CHG_IN_OP_LIAB,
                        CHG_IN_OP_ASST,
                        DEPR_AND_AMORT_DEPLETION,
                        CAPITAL_EXPENDITURES,
                        CHG_IN_RECEIVABLES,
                        CHG_IN_INVENTORY,
                        PROFIT,
                        CASHFLOW_INVEST,
                        CASHFLOW_FINANCING,
                        ST_DEBT_REPAY_PROC,
                        COM_STCK_REPUR_PAYM,
                        EQUITY_REPUR_PAYM,
                        PREF_STCK_REPUR_PAYM,
                        DIV_PAYOUT,
                        DIV_PAYOUT_COM_STCK,
                        DIV_PAYOUT_PREF_STCK,
                        COM_STCK_ISSUE_PROC,
                        LT_DEBT_ISSUE_PROCEEDS,
                        PREF_STOCK_ISSUE_PROC,
                        EQUITY_REPUR_PROC,
                        TRES_STOCK_SALE_PROC,
                        CHG_IN_CSH_EQUIV,
                        CHG_IN_EXCHG_RT,
                        NET_INCOME,
                        CREATE_ID,
                        CREATE_TS,
                        UPDATE_ID,
                        UPDATE_TS
                FROM STATEMENTS.CASH_FLOW
                WHERE SYMBOL = COALESCE(P_SYMBOL_I, SYMBOL)
                  AND FISCAL_DATE_END = COALESCE(P_FISCAL_DATE_END_I, FISCAL_DATE_END);
    EXCEPTION
        WHEN OTHERS THEN
            RAISE EXCEPTION 'STATEMENTS_API_DBO.api_fetch_cash_flows (%)', SQLERRM;
END;
$$ LANGUAGE plpgsql;
