CREATE TABLE STATEMENTS.RATIOS_DELTA(SYMBOL VARCHAR(10),
                                FISCAL_DATE_END DATE,
                                CURRENT_RATIO DECIMAL(3,3),
                                QUICK_RATIO DECIMAL(3,3),
                                DEBT_TO_EQUITY DECIMAL(3,3),
                                INTEREST_COVERGE DECIMAL(3,3),
                                NET_PROFIT_MARGIN DECIMAL(3,3),
                                RETURN_ON_ASSETS DECIMAL(3,3),
                                RETURN_ON_EQUITY DECIMAL(3,3),
                                INVENTORY_TURNOVER DECIMAL(3,3),
                                DAYS_SALES_OUTSTANDING DECIMAL(3,3),
                                PRICE_EARNINGS DECIMAL(3,3),
                                PRICE_BOOK_RATIO DECIMAL(3,3),
                                PRICE_CASHFLOW_RATIO DECIMAL(3,3),
                                DIVIDEND_YIELD DECIMAL(3,3),
                                EV_EBITDA DECIMAL(3,3),
                                FREE_CASHFLOW DECIMAL(3,3),
                                OPERATING_MARGIN DECIMAL(3,3),
                                GROSS_MARGIN DECIMAL(3,3),
                                CASH_CONVERSION_CYCLE DECIMAL(3,3),
                                CREATE_ID VARCHAR(10),
                                CREATE_TS TIMESTAMP,
                                UPDATE_ID VARCHAR(10),
                                UPDATE_TS TIMESTAMP,
                                PRIMARY KEY (SYMBOL, FISCAL_DATE_END)
);